defaults:
  - model@model: naim  # Default model
  - data@data: tbi      # Default dataset
  - _self_

# General settings
seed: 42
device: cuda
output_dir: outputs_for_tables

# Training settings
training:
  num_epochs: 100
  batch_size: 32
  learning_rate: 0.001
  early_stopping:
    patience: 10
    monitor: val_loss
    
# Validation settings
validation:
  split_ratio: 0.2
  kfold: 5

# Logging settings  
logging:
  sweep : false
  wandb:
    project: naim
    entity: naim
    name: naim
    tags: [naim, tbi]
    group: naim
    notes: "NAIM model for TBI dataset"
    config:
      model: naim
      dataset: tbi
      batch_size: ${default_sweep.training.batch_size}
      learning_rate: ${default_sweep.training.learning_rate}
      num_epochs: ${default_sweep.training.num_epochs}
  log_interval: 100
  save_interval: 10 