defaults:
  - model@model: naim_text  # Default model
  - data@data: naim_text   # Default dataset
  - _self_

# General settings
seed: 42
device: cuda
output_dir: outputs

# Training settings
training:
  num_epochs: 100
  batch_size: 8
  learning_rate: 0.006937198828044247
  early_stopping:
    patience: 10
    monitor: val_loss

# Validation settings
validation:
  split_ratio: 0.2
  kfold: 5

# Logging settings  
logging:
  sweep: true
  wandb:
    project: naim_tbi
    entity: naim
    name: multimodal_final
    tags: [naim, tbi]
    group: naim_sweep
    notes: "NAIM model for TBI dataset"
  log_interval: 100
  save_interval: 10
  sweep_count : 5
sweep_configuration:
  method: grid
  metric:
    name: val_loss
    goal: minimize
  parameters:
    learning_rate:
      values: [0.001, 0.01, 0.1]
    batch_size:
      values: [16, 32, 64]
    num_epochs:
      values: [50, 100]
    early_stopping_patience:
      values: [5, 10]