name: naim
model:
  _target_: src.models.viTBI.viTBI
  params:
    pretrained_model_name : demdecuong/vihealthbert-base-word
    num_classes: 4 
    dropout_rate : 0.1
    num_layers: 3

optimizer:
  lr: ${training.learning_rate}
  betas: [ 0.9, 0.999 ]
  eps: 1e-8   
  weight_decay: 0.01
  amsgrad: False
  foreach: null
  maximize: False
  capturable: False
scheduler:
  T_max: ${training.num_epochs}
  eta_min: 1e-6 
  mode: min
  factor: 0.1
  patience: 10
  verbose: False
