_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 50
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 50
                - 53
                - 55
            "3":
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.9
            "6": 4.50.3
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
