defaults:
  - model@model: naim_text  # Default model
  - data@data: naim_text    # Default dataset
  - _self_

# General settings
seed: 42
device: cuda
output_dir: outputs

# Training settings
training:
  num_epochs: 100
  batch_size: 16
  learning_rate: 0.012294735396516012
  early_stopping:
    patience: 10
    monitor: val_loss
    
# Validation settings
validation:
  split_ratio: 0.2
  kfold: 5

logging:
  log_interval: 100
  save_interval: 10
  wandb:
    project: naim_tbi
    entity: naim
    name:  naim_run_${now:%m-%d_%H-%M}
    tags: [naim, tbi]
    group: naim_sweep
    notes: "NAIM model for TBI dataset"