name: naim
model:
  _target_: src.models.naim.NAIMclassifier
  params:
    input_size: ${data.num_features}
    output_size: ${data.num_classes}
    cat_idxs: null
    cat_dims: null
    d_token: 6
    embedder_initialization: normal
    bias: false
    mask_type: 2
    missing_value: ~inf
    num_heads: 2
    feedforward_dim: 1000
    dropout_rate: 0.0
    activation: relu
    num_layers: 5
    extractor: false

optimizer:
  lr: 0.001
  betas: [ 0.9, 0.999 ]
  eps: 1e-8   
  weight_decay: 0.01
  amsgrad: False
  foreach: null
  maximize: False
  capturable: False
scheduler:
  T_max: ${training.num_epochs}
  eta_min: 1e-6 
  mode: min
  factor: 0.1
  patience: 10
  verbose: False
