defaults:
  - model@model: vitbi  # Default model
  - data@data: tbi_text      # Default dataset
  - _self_

# General settings
seed: 42
device: cuda
output_dir: outputs

# Training settings
training:
  num_epochs: 100
  batch_size: 32
  learning_rate: 0.001
  early_stopping:
    patience: 10
    monitor: val_loss
    
# Validation settings
validation:
  split_ratio: 0.2
  kfold: 5

# Logging settings  
logging:
  log_interval: 100
  save_interval: 10 